### ISSUE TITLE
Audit Idea: Detect repeated rules in the CSS

### ISSUE THREAD

**Issue by ryelle** [ryelle/css-audit#20]
If we run this over a file, it should pull out any place where a `property: value;` repeats. For example, this should return `[ 'border: 1px solid red' ]`.

```css
.foo {
    padding: 20px;
    border: 1px solid red;
}
.bar {
    padding: 10px;
    border: 1px solid red;
}
```

**Comment by ryelle** [comment]
Try looking at [`postcss-discard-duplicates`](https://github.com/cssnano/cssnano/tree/master/packages/postcss-discard-duplicates) for inspiration on how to do this.

**Comment by ryelle** [comment]
The flip side to this could be checking for repeated selectors - so this would return `[ .foo ]`.

```css
.foo {
    border: 1px solid red;
}
.foo {
    display: grid;
}
```
